# Warp routes for DTCC Besu ↔ L2 (op-reth) bridge
---
tokens:
  - chainName: dtccbesu
    standard: EvmHypNative
    addressOrDenom: "0x0Eb3cdE9018154eD1A2fC4263934b0Cb1b0c9f13"
    decimals: 18
    symbol: ETH
    name: Ether
    connections:
      - token: "ethereum|l2local|0x3Ae6De8f252D24bd87b9817aF4eEbE8E2Ba8236E"
  - chainName: l2local
    standard: EvmHypNative
    addressOrDenom: "0x3Ae6De8f252D24bd87b9817aF4eEbE8E2Ba8236E"
    decimals: 18
    symbol: ETH
    name: Ether
    connections:
      - token: "ethereum|dtccbesu|0x0Eb3cdE9018154eD1A2fC4263934b0Cb1b0c9f13"
options: {}
