#!/bin/bash
# Deploy Hyperlane bridge infrastructure for L1<->L2 bridging
# Usage: ./scripts/deploy-hyperlane.sh
#
# Prerequisites:
#   - Running L1 (Anvil) and L2 (op-reth) stack
#   - Node.js >= 18

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
HYPERLANE_DIR="$PROJECT_DIR/contracts/hyperlane"
OUTPUT_DIR="$PROJECT_DIR/output/hyperlane"

# Deployer key (Anvil account 0)
export HYP_KEY="${HYP_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"

# RPC URLs
L1_RPC="${L1_RPC:-http://localhost:18545}"
L2_RPC="${L2_RPC:-http://localhost:13000}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js is required but not installed"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        log_error "Node.js >= 18 required, found v$NODE_VERSION"
        exit 1
    fi

    # Check npm/npx
    if ! command -v npx &> /dev/null; then
        log_error "npx is required but not installed"
        exit 1
    fi

    # Check cast (for verification)
    if ! command -v cast &> /dev/null; then
        log_warn "cast (foundry) not found - verification steps will be skipped"
    fi

    log_info "Prerequisites OK"
}

# Check RPC connectivity
check_rpcs() {
    log_info "Checking RPC connectivity..."

    # Check L1
    if ! curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
        "$L1_RPC" | grep -q "0x1"; then
        log_error "Cannot connect to L1 at $L1_RPC"
        exit 1
    fi
    log_info "L1 OK (chainId: 1)"

    # Check L2 (chainId 42069 = 0xa455)
    if ! curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
        "$L2_RPC" | grep -q "0xa455"; then
        log_error "Cannot connect to L2 at $L2_RPC"
        exit 1
    fi
    log_info "L2 OK (chainId: 42069)"
}

# Install Hyperlane CLI
install_hyperlane_cli() {
    log_info "Checking Hyperlane CLI..."

    # Check if already installed globally
    if command -v hyperlane &> /dev/null; then
        VERSION=$(hyperlane --version 2>/dev/null || echo "unknown")
        log_info "Hyperlane CLI already installed: $VERSION"
        return 0
    fi

    log_info "Installing Hyperlane CLI..."
    npm install -g @hyperlane-xyz/cli@latest

    if command -v hyperlane &> /dev/null; then
        VERSION=$(hyperlane --version 2>/dev/null || echo "unknown")
        log_info "Hyperlane CLI installed: $VERSION"
    else
        log_error "Failed to install Hyperlane CLI"
        exit 1
    fi
}

# Create output directory
setup_output_dir() {
    mkdir -p "$OUTPUT_DIR"
    log_info "Output directory: $OUTPUT_DIR"
}

# Register custom chains with Hyperlane
register_chains() {
    log_info "Registering custom chains with Hyperlane..."

    # Create Hyperlane registry directory
    REGISTRY_DIR="$HOME/.hyperlane"
    mkdir -p "$REGISTRY_DIR/chains/l1"
    mkdir -p "$REGISTRY_DIR/chains/l2"

    # Copy chain metadata
    cp "$HYPERLANE_DIR/chains/l1/metadata.yaml" "$REGISTRY_DIR/chains/l1/metadata.yaml"
    cp "$HYPERLANE_DIR/chains/l2/metadata.yaml" "$REGISTRY_DIR/chains/l2/metadata.yaml"

    log_info "Chains registered in $REGISTRY_DIR"
}

# Generate core deployment config
generate_core_config() {
    log_info "Generating core deployment config..."

    cat > "$OUTPUT_DIR/core-config.yaml" << 'EOF'
# Hyperlane Core Deployment Config
# Generated by deploy-hyperlane.sh

l1:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  defaultIsm:
    type: trustedRelayerIsm
    relayer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  defaultHook:
    type: merkleTreeHook
  requiredHook:
    type: protocolFee
    owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    maxProtocolFee: "100000000000000000"
    protocolFee: "0"

l2:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  defaultIsm:
    type: trustedRelayerIsm
    relayer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  defaultHook:
    type: merkleTreeHook
  requiredHook:
    type: protocolFee
    owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    maxProtocolFee: "100000000000000000"
    protocolFee: "0"
EOF

    log_info "Core config written to $OUTPUT_DIR/core-config.yaml"
}

# Deploy core contracts
deploy_core() {
    log_info "Deploying Hyperlane core contracts..."

    cd "$PROJECT_DIR"

    # Deploy to L1 and L2
    # The CLI will prompt for confirmation - we use yes to auto-confirm
    yes | hyperlane core deploy \
        --targets l1,l2 \
        --config "$OUTPUT_DIR/core-config.yaml" \
        --registry "$HOME/.hyperlane" \
        --overrides "$HYPERLANE_DIR/chains" \
        2>&1 | tee "$OUTPUT_DIR/core-deploy.log"

    log_info "Core deployment complete. Check $OUTPUT_DIR/core-deploy.log"
}

# Generate warp route config with deployed addresses
generate_warp_config() {
    log_info "Generating warp route config..."

    cat > "$OUTPUT_DIR/warp-config.yaml" << 'EOF'
# Hyperlane Warp Route Configuration
# ETH bridging between L1 and L2

tokens:
  - chainName: l1
    standard: EvmHypNative
    name: "Ether"
    symbol: "ETH"
    decimals: 18

  - chainName: l2
    standard: EvmHypNative
    name: "Ether"
    symbol: "ETH"
    decimals: 18
EOF

    log_info "Warp config written to $OUTPUT_DIR/warp-config.yaml"
}

# Deploy warp route
deploy_warp() {
    log_info "Deploying Hyperlane warp route..."

    cd "$PROJECT_DIR"

    # Deploy warp route
    yes | hyperlane warp deploy \
        --config "$OUTPUT_DIR/warp-config.yaml" \
        --registry "$HOME/.hyperlane" \
        2>&1 | tee "$OUTPUT_DIR/warp-deploy.log"

    log_info "Warp deployment complete. Check $OUTPUT_DIR/warp-deploy.log"
}

# Extract and save deployed addresses
save_addresses() {
    log_info "Saving deployed addresses..."

    # The Hyperlane CLI saves deployment artifacts to ~/.hyperlane/
    # Copy relevant files to our output directory
    if [ -d "$HOME/.hyperlane/chains/l1" ]; then
        cp -r "$HOME/.hyperlane/chains/l1" "$OUTPUT_DIR/" 2>/dev/null || true
    fi
    if [ -d "$HOME/.hyperlane/chains/l2" ]; then
        cp -r "$HOME/.hyperlane/chains/l2" "$OUTPUT_DIR/" 2>/dev/null || true
    fi

    # Create a summary file
    cat > "$OUTPUT_DIR/addresses.json" << EOF
{
  "deployedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "deployer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  "l1": {
    "chainId": 1,
    "rpcUrl": "$L1_RPC"
  },
  "l2": {
    "chainId": 42069,
    "rpcUrl": "$L2_RPC"
  },
  "note": "Check ~/.hyperlane/ for full deployment artifacts"
}
EOF

    log_info "Addresses saved to $OUTPUT_DIR/addresses.json"
}

# Verify deployment
verify_deployment() {
    log_info "Verifying deployment..."

    if ! command -v cast &> /dev/null; then
        log_warn "Skipping verification (cast not available)"
        return 0
    fi

    # Check if deployments directory exists with artifacts
    if [ -f "$HOME/.hyperlane/chains/l1/addresses.yaml" ]; then
        log_info "L1 deployment artifacts found"
    else
        log_warn "L1 deployment artifacts not found at expected location"
    fi

    if [ -f "$HOME/.hyperlane/chains/l2/addresses.yaml" ]; then
        log_info "L2 deployment artifacts found"
    else
        log_warn "L2 deployment artifacts not found at expected location"
    fi

    log_info "Verification complete"
}

# Print summary
print_summary() {
    echo ""
    echo "=============================================="
    echo "Hyperlane Bridge Deployment Complete"
    echo "=============================================="
    echo ""
    echo "Deployment artifacts: $OUTPUT_DIR/"
    echo "Hyperlane registry:   $HOME/.hyperlane/"
    echo ""
    echo "Next steps:"
    echo "  1. Start the relayer:"
    echo "     docker compose --profile bridge up -d hyperlane-relayer"
    echo ""
    echo "  2. Test bridging L1 -> L2:"
    echo "     ./scripts/bridge-deposit.sh 1"
    echo ""
    echo "  3. Test bridging L2 -> L1:"
    echo "     ./scripts/bridge-withdraw.sh 1"
    echo ""
    echo "  4. Monitor relayer logs:"
    echo "     docker compose logs -f hyperlane-relayer"
    echo ""
}

# Main
main() {
    echo ""
    echo "=============================================="
    echo "Hyperlane Bridge Deployment"
    echo "=============================================="
    echo ""

    check_prerequisites
    check_rpcs
    install_hyperlane_cli
    setup_output_dir
    register_chains
    generate_core_config
    deploy_core
    generate_warp_config
    deploy_warp
    save_addresses
    verify_deployment
    print_summary
}

main "$@"
