#!/bin/bash
# Generate bytecode.go from Foundry compilation and npm packages
#
# Usage: ./scripts/generate-bytecode.sh
#
# This script:
# 1. Compiles local Solidity contracts (WETH9, MockUSDC) using Foundry
# 2. Extracts Uniswap V3 bytecodes from npm packages
# 3. Generates ../loadgenerator/internal/uniswapv3/bytecode_generated.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUT_FILE="$ROOT_DIR/../loadgenerator/internal/uniswapv3/bytecode_generated.go"
NPM_DIR="$ROOT_DIR"

cd "$ROOT_DIR"

echo "=== Compiling local contracts with Foundry ==="
forge build --force

echo "=== Extracting local bytecodes ==="

extract_foundry_bytecode() {
    local contract_name="$1"
    local json_file="$ROOT_DIR/out/${contract_name}.sol/${contract_name}.json"

    if [[ ! -f "$json_file" ]]; then
        echo "ERROR: $json_file not found" >&2
        exit 1
    fi

    jq -r '.bytecode.object' "$json_file"
}

WETH9_BYTECODE=$(extract_foundry_bytecode "WETH9")
MOCKUSDC_BYTECODE=$(extract_foundry_bytecode "MockUSDC")

echo "=== Extracting Uniswap V3 bytecodes from npm ==="

# Install Uniswap V3 packages if not present
if [[ ! -d "$NPM_DIR/node_modules/@uniswap/v3-core" ]]; then
    echo "Installing @uniswap/v3-core and @uniswap/v3-periphery..."
    cd "$NPM_DIR"
    npm install @uniswap/v3-core@1.0.1 @uniswap/v3-periphery@1.4.4 --save-exact
    cd "$ROOT_DIR"
fi

extract_npm_bytecode() {
    local package="$1"
    local artifact="$2"
    local json_file="$NPM_DIR/node_modules/@uniswap/$package/artifacts/contracts/$artifact"

    if [[ ! -f "$json_file" ]]; then
        echo "ERROR: $json_file not found" >&2
        exit 1
    fi

    jq -r '.bytecode' "$json_file"
}

FACTORY_BYTECODE=$(extract_npm_bytecode "v3-core" "UniswapV3Factory.sol/UniswapV3Factory.json")
SWAPROUTER_BYTECODE=$(extract_npm_bytecode "v3-periphery" "SwapRouter.sol/SwapRouter.json")
NFTMANAGER_BYTECODE=$(extract_npm_bytecode "v3-periphery" "NonfungiblePositionManager.sol/NonfungiblePositionManager.json")

cd "$ROOT_DIR"

echo "=== Generating $OUT_FILE ==="

cat > "$OUT_FILE" << 'HEADER'
// Code generated by scripts/generate-bytecode.sh. DO NOT EDIT.
//
// Local contracts compiled with Foundry (Solidity 0.8.20, optimizer 200 runs):
//   - WETH9 from src/WETH9.sol
//   - MockUSDC from src/MockUSDC.sol
//
// Uniswap V3 contracts from npm packages:
//   - UniswapV3Factory from @uniswap/v3-core@1.0.1
//   - SwapRouter from @uniswap/v3-periphery@1.4.4
//   - NonfungiblePositionManager from @uniswap/v3-periphery@1.4.4

package uniswapv3

import "github.com/ethereum/go-ethereum/common"

HEADER

cat >> "$OUT_FILE" << EOF
// WETH9Bytecode is Wrapped ETH contract bytecode.
var WETH9Bytecode = common.FromHex("$WETH9_BYTECODE")

// MockUSDCBytecode is a simple mintable ERC20 token bytecode.
var MockUSDCBytecode = common.FromHex("$MOCKUSDC_BYTECODE")

// UniswapV3FactoryBytecode is the Uniswap V3 factory contract.
var UniswapV3FactoryBytecode = common.FromHex("$FACTORY_BYTECODE")

// SwapRouterBytecode is the Uniswap V3 swap router contract.
// Constructor args: (factory address, WETH9 address)
var SwapRouterBytecode = common.FromHex("$SWAPROUTER_BYTECODE")

// NonfungiblePositionManagerBytecode is the Uniswap V3 NFT position manager.
// Constructor args: (factory address, WETH9 address, token descriptor address)
var NonfungiblePositionManagerBytecode = common.FromHex("$NFTMANAGER_BYTECODE")
EOF

echo "Generated $OUT_FILE"
echo "  WETH9: ${#WETH9_BYTECODE} chars"
echo "  MockUSDC: ${#MOCKUSDC_BYTECODE} chars"
echo "  UniswapV3Factory: ${#FACTORY_BYTECODE} chars"
echo "  SwapRouter: ${#SWAPROUTER_BYTECODE} chars"
echo "  NonfungiblePositionManager: ${#NFTMANAGER_BYTECODE} chars"
