#!/usr/bin/env bash
#
# start-agglayer.sh - Start AggLayer FEP stack with op-reth
#
# Usage:
#   ./scripts/start-agglayer.sh          # Start with contract deployment
#   ./scripts/start-agglayer.sh --skip-deploy  # Skip contract deployment
#
# This script:
# 1. Starts base infrastructure (L1, L2, block-builder)
# 2. Deploys AggLayer contracts to L1 (optional)
# 3. Updates config files with contract addresses
# 4. Starts AggLayer services
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${CYAN}[STEP]${NC} ${BOLD}$1${NC}"; }

SKIP_DEPLOY=false
for arg in "$@"; do
    case $arg in
        --skip-deploy)
            SKIP_DEPLOY=true
            ;;
    esac
done

echo ""
echo -e "${BOLD}════════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}              AggLayer FEP Stack Startup                         ${NC}"
echo -e "${BOLD}════════════════════════════════════════════════════════════════${NC}"
echo ""

# Create required directories
mkdir -p output/contracts
mkdir -p config/keystore

# Create sequencer keystore if not exists
if [ ! -f config/keystore/sequencer.key ]; then
    log_info "Creating sequencer keystore..."
    # Use Anvil's default private key
    echo "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" > config/keystore/sequencer.key
fi

# ============================================================================
# Step 1: Start base infrastructure
# ============================================================================
log_step "Starting base infrastructure (L1, L2, block-builder)..."

docker compose up -d l1 l2-reth block-builder dashboard

log_info "Waiting for L1 to be healthy..."
until docker exec sequencer-poc-l1 cast chain-id --rpc-url http://localhost:8545 > /dev/null 2>&1; do
    sleep 2
done
log_ok "L1 is ready"

log_info "Waiting for L2 to start..."
sleep 10  # op-reth takes time to initialize
log_ok "L2 started"

# ============================================================================
# Step 2: Deploy contracts (optional)
# ============================================================================
if [ "$SKIP_DEPLOY" = false ]; then
    log_step "Deploying AggLayer contracts to L1..."

    # Note: The agglayer-contracts image expects specific environment
    # For now, we'll use placeholder addresses until we can properly deploy
    log_warn "Contract deployment not fully automated yet."
    log_warn "Using placeholder addresses for development."
    log_info "For production, run: docker compose --profile agglayer-deploy up agglayer-contracts"

    # Set default contract addresses (these would be replaced by actual deployment)
    # These are commonly used test addresses from kurtosis-cdk
    export L1_BRIDGE_ADDRESS="0xFe12ABaa190Ef0c8638Ee0ba9F828BF41368Ca0E"
    export L2_BRIDGE_ADDRESS="0xFe12ABaa190Ef0c8638Ee0ba9F828BF41368Ca0E"
    export ROLLUP_MANAGER_ADDRESS="0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
    export GLOBAL_EXIT_ROOT_ADDRESS="0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
    export ROLLUP_ADDRESS="0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"

    # Save addresses to file
    cat > output/contracts/addresses.env << EOF
# AggLayer Contract Addresses
# Generated by start-agglayer.sh
L1_BRIDGE_ADDRESS=${L1_BRIDGE_ADDRESS}
L2_BRIDGE_ADDRESS=${L2_BRIDGE_ADDRESS}
ROLLUP_MANAGER_ADDRESS=${ROLLUP_MANAGER_ADDRESS}
GLOBAL_EXIT_ROOT_ADDRESS=${GLOBAL_EXIT_ROOT_ADDRESS}
ROLLUP_ADDRESS=${ROLLUP_ADDRESS}
EOF
    log_ok "Contract addresses saved to output/contracts/addresses.env"
else
    log_info "Skipping contract deployment..."
    if [ -f output/contracts/addresses.env ]; then
        source output/contracts/addresses.env
        log_ok "Loaded existing contract addresses"
    else
        log_warn "No contract addresses found. AggLayer may not work correctly."
    fi
fi

# ============================================================================
# Step 3: Start AggLayer services
# ============================================================================
log_step "Starting AggLayer services..."

# Export contract addresses for docker compose
export L1_BRIDGE_ADDRESS="${L1_BRIDGE_ADDRESS:-0x0000000000000000000000000000000000000000}"
export L2_BRIDGE_ADDRESS="${L2_BRIDGE_ADDRESS:-0x0000000000000000000000000000000000000000}"
export ROLLUP_MANAGER_ADDRESS="${ROLLUP_MANAGER_ADDRESS:-0x0000000000000000000000000000000000000000}"
export ROLLUP_ADDRESS="${ROLLUP_ADDRESS:-0x0000000000000000000000000000000000000000}"

docker compose --profile agglayer up -d

log_info "Waiting for services to initialize..."

# Wait for PostgreSQL
log_info "Waiting for PostgreSQL..."
until docker exec sequencer-poc-postgres pg_isready -U agglayer > /dev/null 2>&1; do
    sleep 2
done
log_ok "PostgreSQL is ready"

# Wait for AggLayer
log_info "Waiting for AggLayer (this may take a minute)..."
retries=0
max_retries=30
until curl -sf http://localhost:15577/health > /dev/null 2>&1; do
    retries=$((retries + 1))
    if [ $retries -ge $max_retries ]; then
        log_warn "AggLayer health check timed out. Check logs with: docker compose logs agglayer"
        break
    fi
    sleep 5
done
if [ $retries -lt $max_retries ]; then
    log_ok "AggLayer is ready"
fi

# ============================================================================
# Done
# ============================================================================
echo ""
echo -e "${BOLD}════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}              AggLayer FEP Stack Started!                       ${NC}"
echo -e "${BOLD}════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}Service URLs:${NC}"
echo "  L1 (Anvil):          http://localhost:18545"
echo "  L2 (op-reth):        http://localhost:18546"
echo "  Block Builder:       http://localhost:13000"
echo "  Dashboard:           http://localhost:18000"
echo ""
echo "  AggLayer RPC:        http://localhost:15577"
echo "  AggLayer gRPC:       localhost:14443"
echo "  Bridge Service:      http://localhost:18080"
echo "  Bridge UI:           http://localhost:18088"
echo ""
echo -e "${CYAN}Quick Commands:${NC}"
echo "  # Check AggLayer health"
echo "  curl http://localhost:15577/health"
echo ""
echo "  # View logs"
echo "  docker compose logs -f agglayer"
echo "  docker compose logs -f aggkit"
echo ""
echo "  # Stop all services"
echo "  docker compose --profile agglayer down"
echo ""
echo -e "${YELLOW}Note:${NC} Contract deployment is not fully automated."
echo "      Bridging requires properly deployed contracts on L1 and L2."
echo "      See docs.agglayer.dev for full deployment guide."
echo ""
